version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    image: api-exceltic
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      spring.application.name: apiExceltic.sergioMostacero
      spring.datasource.url: jdbc:postgresql://postgres:5432/postgres 
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      server.port: 8000
      spring.jpa.hibernate.ddl-auto: update
